trade_your_goods_infrastructure:
    resource: "@TradeYourGoodsInfrastructureBundle/Resources/config/routing.yml"
    prefix:   /

trade_your_goods_web:
    resource: "@TradeYourGoodsWebBundle/Resources/config/routing.yml"
    prefix:   /

trade_your_goods_rest:
    resource: "@TradeYourGoodsRestBundle/Resources/config/routing.yml"
    prefix:   /
