trade_your_goods_web_homepage:
    path:     /
    defaults: { _controller: TradeYourGoodsWebBundle:Login:index }

trade_your_goods_login:
    path:     /login
    defaults: { _controller: TradeYourGoodsWebBundle:Login:check }

