trade_your_goods_index:
    path:     /
    defaults: { _controller: TradeYourGoodsWebBundle:Login:index }

trade_your_goods_login:
    path:     /login
    defaults: { _controller: TradeYourGoodsWebBundle:Login:check }

trade_your_goods_register_new:
    path:     /register_new
    defaults: { _controller: TradeYourGoodsWebBundle:Register:new }

trade_your_goods_register:
    path:     /register
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TradeYourGoodsWebBundle:Login:register.html.php'

trade_your_goods_homepage:
    path:     /homepage
    defaults:
        _controller: TradeYourGoodsWebBundle:Homepage:index

trade_your_goods_advert:
    path:     /advert
    defaults:
        _controller: TradeYourGoodsWebBundle:Advert:index
        
trade_your_goods_create_advert:
    path:     /create_advert
    defaults:
        _controller: TradeYourGoodsWebBundle:Advert:create
        
trade_your_goods_new_advert:
    path:     /new_advert
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    'TradeYourGoodsWebBundle:Advert:newadvert.html.php'
        


